**EASY QUESTIONS**

In [ ]:
import pandas as pd

# Define the dictionary with student details
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
}

# Create the DataFrame
student_df = pd.DataFrame(data)

# Display the DataFrame
print(student_df)

      Name  Age         City
0    Alice   20     New York
1      Bob   21  Los Angeles
2  Charlie   19      Chicago
3    David   22      Houston

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
}

student_df = pd.DataFrame(data)


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)


print(student_df)

      Name  Age         City
0    Alice   20     New York
1      Bob   21  Los Angeles
2  Charlie   19      Chicago
3    David   22      Houston

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
}

student_df = pd.DataFrame(data)

print(student_df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
#QU4
import pandas as pd

# 1. Create a sample student DataFrame
data = {
    'StudentID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [20, 21, 19, 22],
    'Grade': ['A', 'B', 'A', 'C']
}
student_df = pd.DataFrame(data)
print("--- Full DataFrame ---")
display(student_df)
name_series = student_df['Name']

print("\n--- 'Name' Column (as Series) ---")
display(name_series)
name_df = student_df[['Name']]

print("\n--- 'Name' Column (as DataFrame) ---")
display(name_df)

--- Full DataFrame ---

   StudentID     Name  Age Grade
0        101    Alice   20     A
1        102      Bob   21     B
2        103  Charlie   19     A
3        104    David   22     C

--- 'Name' Column (as Series) ---

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

--- 'Name' Column (as DataFrame) ---

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [ ]:
#qu5
from pandas import Series

population = Series([35, 42, 31], index=['Delhi', 'Mumbai', 'Jaipur'])
jaipur_pop = population['Jaipur']
print(jaipur_pop)

31

In [ ]:
#qu6
from pandas import Series

score = Series([35, 68, 44, 79, 52])
print(score[score > 50])

1    68
3    79
4    52
dtype: int64

In [ ]:
#qu7
from pandas import Series

subjects = Series([76, 83, 91], index=['Physics', 'Chemistry', 'Maths'])
print('Chemistry' in subjects.index)

True

In [ ]:
#qu8
from pandas import Series

subjects = Series([76, 83, 91], index=['Physics', 'Chemistry', 'Maths'])
subjects_dict = subjects.to_dict()

print(subjects_dict)

{'Physics': 76, 'Chemistry': 83, 'Maths': 91}

In [ ]:
#qu9
import pandas as pd

prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
price_series = pd.Series(prices)

print(price_series)

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
#qu10
import pandas as pd

prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
price_series = pd.Series(prices)

# Displaying the index explicitly
print(price_series.index)